version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - childfoundation_static_volume:/childfoundation/static
      - childfoundation_files_volume:/childfoundation/files
    networks:
      - nginx_network

volumes:
  childfoundation_static_volume:
    external: true
  childfoundation_files_volume:
    external: true
networks:
  nginx_network:
    external: true