
version: '2'

services:
  childfoundation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/childfoundation
      - childfoundation_static_volume:/childfoundation/static
      - childfoundation_files_volume:/childfoundation/files
    restart: always
    ports:
      - "8000:8000"
    networks:
      - childfoundation_network
      - nginx_network
    depends_on:
      - childfoundation_postgresql
  childfoundation_postgresql:
    image: postgres:13
    container_name: childfoundation_postgresql
    volumes:
      - childfoundation_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - childfoundation_network

volumes:
  childfoundation_postgresql:
    external: true
  childfoundation_static_volume:
    external: true
  childfoundation_files_volume:
    external: true
networks:
  childfoundation_network:
    external: true
  nginx_network:
    external: true